name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
